# Generated by Django 5.0.3 on 2024-04-11 14:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Epreuve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre de l’épreuve')),
                ('description', models.TextField(verbose_name='Description de l’épreuve')),
                ('date_epreuve', models.DateField(verbose_name='Date de l’épreuve')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='imgbank')),
            ],
        ),
        migrations.CreateModel(
            name='OffreBillet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('SOLO', 'Solo'), ('DUO', 'Duo'), ('FAMILLE', 'Famille')], max_length=100, unique=True, verbose_name='Type d’offre')),
                ('description', models.TextField(blank=True, verbose_name='Description de l’offre')),
                ('prix', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Prix de l’offre')),
                ('nombre_personnes', models.PositiveIntegerField(verbose_name='Nombre de personne par billet')),
            ],
        ),
    ]
