# Generated by Django 5.0.3 on 2024-04-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offrebillet',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
