# Generated by Django 5.0.6 on 2024-05-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epreuve',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
