# Generated by Django 5.0.6 on 2024-05-22 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_epreuve_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offrebillet',
            name='epreuve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='store.epreuve', verbose_name='Épreuve associée'),
        ),
    ]
