# Generated by Django 5.0.3 on 2024-04-18 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_offrebillet_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='epreuve',
            old_name='thumbnail',
            new_name='illustration',
        ),
    ]
