# Generated by Django 5.0.6 on 2024-05-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_offrebillet_epreuve'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='payé',
            field=models.BooleanField(default=False),
        ),
    ]
