# Generated by Django 5.0.3 on 2024-04-25 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_order_achat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='achat',
            old_name='ordered',
            new_name='acheté',
        ),
        migrations.RenameField(
            model_name='achat',
            old_name='quantity',
            new_name='quantité',
        ),
        migrations.RenameField(
            model_name='achat',
            old_name='user',
            new_name='utilisateur',
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acheté', models.BooleanField(default=False)),
                ('date_achat', models.DateTimeField(blank=True, null=True)),
                ('achats', models.ManyToManyField(to='store.achat')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
