# Generated by Django 5.0.3 on 2024-04-29 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_ordered_achat_acheté_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achat',
            old_name='produit',
            new_name='billet',
        ),
    ]
