# Generated by Django 5.0.3 on 2024-04-29 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_rename_produit_achat_billet'),
    ]

    operations = [
        migrations.AddField(
            model_name='offrebillet',
            name='epreuve',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='store.epreuve', verbose_name='Épreuve associée'),
        ),
    ]
