# Generated by Django 5.0.3 on 2024-05-02 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_panier_utilisateur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panier',
            name='achats',
        ),
        migrations.AddField(
            model_name='achat',
            name='panier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.panier'),
        ),
    ]
