# Generated by Django 5.0.3 on 2024-05-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_panier_achats_achat_panier'),
    ]

    operations = [
        migrations.AddField(
            model_name='epreuve',
            name='type',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Type d’épreuve'),
        ),
    ]
