# Generated by Django 5.0.3 on 2024-05-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_epreuve_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='epreuve',
            name='mention',
            field=models.TextField(blank=True, null=True, verbose_name='Mentions'),
        ),
    ]
