# Generated by Django 5.0.6 on 2024-05-20 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achat',
            name='panier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achats', to='store.panier'),
        ),
    ]
