# Generated by Django 5.0.6 on 2024-05-17 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_nom_customuser_prenom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='nom',
            new_name='Nom',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='prenom',
            new_name='Prénom',
        ),
    ]
