# Generated by Django 5.0.6 on 2024-05-17 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_nom_customuser_nom_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='Nom',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='Prénom',
            new_name='prenom',
        ),
    ]
