# Generated by Django 5.0.6 on 2024-05-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_nom_customuser_nom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='nom',
            field=models.CharField(blank=True, max_length=30, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='prenom',
            field=models.CharField(blank=True, max_length=30, verbose_name='Prénom'),
        ),
    ]
